### ISSUE TITLE
Perhaps it's possible to add support for sending decoded APRS packages to Navit?

### ISSUE THREAD

**Issue by Supermagnum** [ohanssen/ArcticTracker-ESP32#2]
https://www.navit-project.org/

https://github.com/navit-gps/navit/issues/982

Some ideas:
https://github.com/Supermagnum/Sleipnir

**Comment by ohanssen** [comment]
Sorry that I didn't respont to this before. I think it is an interesting idea. It may also be an idea to use the Polaric Server backend. It has a REST API and Websocket interface.

**Comment by ohanssen** [comment]
https://polaricserver.readthedocs.io

**Comment by Supermagnum** [comment]
Please be aware of:
https://github.com/navit-gps/navit/issues/982
