### ISSUE TITLE
[Feature] the firmware port for LilyGO T-TWR Plus

### ISSUE THREAD

**Issue by lyusupov** [ohanssen/ArcticTracker-ESP32#3]
Thank you for this great project!

Is there any chance to port this APRS firmware for the [**LilyGO T-TWR Plus**](https://www.lilygo.cc/products/t-twr-plus) ?

![](https://www.lilygo.cc/cdn/shop/files/LILYGO-T-TWR-PLUS_2.jpg?v=1686994311)

**This approach can give a lot wider exposure for your firmware since the LilyGO development board is available in large quantities at more or less reasonable price.**

The LilyGO board has some hardware items that are very similar to that the ArcticTracker v.3 uses, such as
- ESP32-S3
- 1.3 inch SH1106 OLED

Please, see the [**schematic file**](https://github.com/Xinyuan-LilyGO/T-TWR/blob/master/schematic/T-TWR-Plus_Rev2.0.pdf) for more details.

 SA868 radio is a little bit different to the FRS one but not a lot, right ?

**Comment by ohanssen** [comment]
Yes, thanks for a interesting idea. There are many similarities so it is probably not too hard to do it so I'll take a look into it.

**Comment by ohanssen** [comment]
I've got a T-TWR, I've tested it and it looks good. I tried to load the Arctic Tracker firmware onto it and it runs. The ESP32 module is the same as the AT, so the console, wifi and storage works without modification. The interfacing to the other hardware need to be adapted though :)

**Comment by ohanssen** [comment]
Status now: Display UI is working. PMU is working (with XPowerLib), battery-status is reported on display, console and REST-API. Charging is ok. GPS is working when it is powered up.

**Comment by lyusupov** [comment]
@ohanssen 

Please, be aware that 

1. effective (approx.) from September, the LilyGO have fixed issue with wrong value of R22 resistor.<br>
    it may still be shown as 4.7K on the schematic file but one should actually **read it as 47K** instead 

<img width="530" alt="image" src="https://github.com/Hamlabs/ArcticTracker-ESP32/assets/5849637/59bc915c-b956-42ee-86ee-9fa41c2328fd">

<br>
<br>

  **Inspect that your T-TWR Plus board uses 47K for the R22 value**. If it is true - it is recommended to NO longer use 11dB as ADC attenuation here:

<img width="502" alt="image" src="https://github.com/Hamlabs/ArcticTracker-ESP32/assets/5849637/d3579653-7f2e-4aa3-a62e-6ede6b0439e6">

<br>
<br>

![](https://github.com/erstec/APRS-ESP/assets/5849637/82b48e80-237c-4b00-92b1-e460da458b66)

<br>
<br>

**For recently manufactured boards it is recommended to use 0 dB attenuation value.**

Older boards _(manufactured before September)_ can be fixed by the R22 replacement:

![](https://user-images.githubusercontent.com/5849637/271892784-080acdf6-d67e-4f29-8cc9-8b7229490c39.png)

<br>
<br>

Read this thread for more details: https://github.com/erstec/APRS-ESP/discussions/29#discussioncomment-7276102

**Comment by lyusupov** [comment]
2. effective from November, the LilyGO is shipping the T-TWR Plus with pre-installed TinyUF2 bootloader:

https://github.com/Xinyuan-LilyGO/T-TWR/blob/master/firmware/README.MD

![](https://github.com/lyusupov/SoftRF/raw/master/documents/images/ham-1.jpg)

Both SoftRF and OpenRTX projects are using UF2 format to deploy the firmware for public:
1) https://github.com/lyusupov/SoftRF/blob/master/software/firmware/binaries/README.md#esp32-s3
2) https://openrtx.org/#/hardware/ttwrplus?id=flashing

It is recommended for the **Arctic Tracker for T-TWR Plus** project to use the **UF2** binary format as well.

**Comment by ohanssen** [comment]
ESP-IDF I guess it is not a big deal to generate the UF2 format. 

Sending packets with the SA868 now works. There is one thing though: There seems to be no connection from the squelch output of the radio-module to the ESP32. It was an easy way to detect that a signal was present on the channel. This can still be done by sampling the ADC input from the radio though. I'll be aware of the resistor.

**Comment by lyusupov** [comment]
Rev 2.0 of the T-TWR Plus does not have the SQL line connected to an ESP32-S3 pin on the PCB.
However, since it is a Dev Kit, one can solder a wire to the pin header manually (when necessary).

Upcoming rev 2.1 of the T-TWR Plus has a certain wiring for the SQL of SA868 to the ESP32-S3 pin as one of added new features.

Video of LilyGO T-TWR Plus **V2.1**: https://twitter.com/lilygo9/status/1752865846727446786
Schematic file: https://github.com/Xinyuan-LilyGO/T-TWR/blob/master/schematic/T-TWR-Plus_Rev2.1.pdf

**Comment by ohanssen** [comment]
Ok, thanks for the info. I will try putting in a wire. I look forward to the 2.1.

**Comment by ohanssen** [comment]
I've put ut a release candidate. I have tested with UF2 bootloader but it failed. I hope to be able to make it available in UF2 format when this issue is solved.

**Comment by lyusupov** [comment]
Øyvind, please, accept my sincere congratulation with completion of the new Release Candidate!

> I have tested with UF2 bootloader but it failed. I hope to be able to make it available in UF2 format when this issue is solved.

The instruction below works good to me.

```
$ uf2conv.py /tmp/ArcticTracker-3.1-rc1.bin -c -f 0xc47e5767 -b 0 -o /tmp/ArcticTracker-3.1-rc1.uf2
Converting to uf2, output size: 2454528, start address: 0x0
Wrote 2454528 bytes to /tmp/ArcticTracker-3.1-rc1.uf2
```

The UF2 output file boots all the way down to the command prompt with T-TWR 2.0 product.

**Comment by lyusupov** [comment]
An attempt to connect to a local Wi-Fi AP gives me the system reset:

```
Welcome to Arctic Tracker 3.1 on ESP32S3, by LA7ECA.

Type 'help' to get the list of commands.
Use UP/DOWN arrows to navigate through command history.
Press TAB when typing command name to auto-complete.
cmd> W (4452) trackstore: Couldn't open file /files/tracks_blk0.bin: No such fiy
W (4452) gptimer: resolution lost, expect 38400, real 38406
W (4452) gptimer: resolution lost, expect 211200, real 211640
cmd>
cmd> wifi on
OK
cmd> wifi-join <MySSID> <MyKEY>
ESP_ERROR_CHECK failed: esp_err_t 0x3002 (ESP_ERR_WIFI_NOT_STARTED) at 0x4200e6e
file: "./components/networking/wifi.c" line 483
func: wifi_join
expression: res

abort() was called at PC 0x4037f9f7 on core 0


Backtrace: 0x4037637e:0x3fca7500 0x4037fa01:0x3fca7520 0x40383fbf:0x3fca7540 0x0




ELF file SHA256: 9e978d11a0d38cbe

Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0x29 (SPI_FAST_FLASH_BOOT)
```

**Comment by ohanssen** [comment]
You may try another command: 

ap 0 `<your-ssid>`  `<your-key>`

I'll take a look at the join command. It is some legacy code - probably not needed anymore.

**Comment by UnderwaterHockey** [comment]
> Ok, thanks for the info. I will try putting in a wire. I look forward to the 2.1.

Any way you can add a pic of where that wire goes to the readme?

**Comment by ohanssen** [comment]
You see one end of the wire in the pic already. The other end is connected to the SQL output of the radio. I plan to publish an article on Hamlabs soon and will put the picture there as well.
![20240320_220606](https://github.com/Hamlabs/ArcticTracker-ESP32/assets/2892992/d5bbc6e6-3156-4ccd-9ee7-95390586fadc)

**Comment by UnderwaterHockey** [comment]
Great, thank you!  I was thinking that shield had to come off to add the wire.

**Comment by lyusupov** [comment]
@ohanssen 

Since you've [released the firmware for the T-TWR Plus](https://github.com/Hamlabs/ArcticTracker-ESP32/releases) recently - I guess it is a good reason to close this GitHub ticket now.

**Comment by lyusupov** [comment]
@ohanssen 

Øyvind , do you have any objections if LilyGO will add a link onto your project's GitHub page on their Store website, like that - 

<img width="526" alt="image" src="https://github.com/Hamlabs/ArcticTracker-ESP32/assets/5849637/2281b526-6c3b-42d7-bd94-fbef9f0fe3cf">

**Comment by ohanssen** [comment]
Ok, I don't see a problem with that.

**Comment by lyusupov** [comment]
> Ok, I don't see a problem with that.

This page contains a reference on Arctic Tracker project -
https://www.lilygo.cc/products/t-twr-plus?variant=42911934185653

<img width="435" alt="image" src="https://github.com/Hamlabs/ArcticTracker-ESP32/assets/5849637/95c2ca77-4a1c-4f8e-8e51-926bf48a0b95">

**Comment by UnderwaterHockey** [comment]
@ohanssen hamlabs.no seems to have been down for a few days now.
