### ISSUE TITLE
Build error: unknown type name 'time_t'

### ISSUE THREAD

**Issue by StephenLKearney** [ohanssen/ArcticTracker-ESP32#6]
I'm trying to flash the firmware with the `idf.py flash` command.  It gets part way through building, then has this error:
`/ArcticTracker-ESP32/main/system.h:32:1: error: unknown type name 'time_t'`
Am I missing some dependency?

I would flash the firmware binaries with the Flash Download Tool (Windows), but I can't get the T-TWR Plus into a state where it will accept the flash.  The only success I've had updating the firmware was with VSCode + PlatformIO, building and uploading the [ESP32APRS_T-TWR project](https://github.com/nakhonthai/ESP32APRS_T-TWR).

Thanks in advance.

**Comment by ohanssen** [comment]
First, what version are you trying to build and flash with idf.py? Is it checked out from the master branch? The include that may be failing (or missing) is
#include <time.h>

When you get this error message, can you see what c-file included the system.h? It may be a good idea to do the include of time.h in the system.h instead of the individual c-files. I'll see if I can fix this. 

When it comes to flashing pre-built code, I have tested this on my Linux machine. How did you try to flash it?

**Comment by StephenLKearney** [comment]
Thanks for the reply.  Yes, I got the master branch (it's the only branch, as far as I can see).  However, I did find the `esptool.py write_flash` command and was able to flash these files to the T_TWR:
```
  0x0 bootloader.bin 
  0x30000 ArcticTracker.bin 
  0x8000 partition-table.bin 
  0x1e000 ota_data_initial.bin 
  0x430000 webapp.bin
```
Now the ArcticTracker firmware v.3.2 is running on my device.  I'm trying to configure it but having trouble with the serial interface.  I tried PuTTY, as suggested in the Readme, and other serial port monitors (Arduino IDE, the Windows app YAT) with settings 9600,8,N.1. In the serial monitor I see ArcticTracker boot and output some messages (see screenshot below), but there is no response when I send `help` or any other text.

![image](https://github.com/user-attachments/assets/ba0fe884-5079-430d-983d-305143f5a2cc)

**Comment by ohanssen** [comment]
It is possible you have to restart the tracker to start the command shell. You will get a prompt when the shell is active. You can just reset it.

**Comment by StephenLKearney** [comment]
What I've found is that the serial interface doesn't respond to commands on Windows but does work on Linux.  My current progress is:

1. Connected to serial interface on Linux machine.
2. Set TXFREQ, RXFREQ, callsign, and AP with my wifi SSID and password.
3. The ESP32 is showing up as a connected client on my wifi router admin page.
4. On the T-TWR screen, the ArcticTracker WIFI page shows that it's connected.
5. I can connect to the web interface.  However, none of the values that I entered in the serial interface, and are displayed on the OLED display, appear in the web interface.  And if I enter settings in the web interface and click Update, they aren't saved to the T-TWR.

And now it's no longer connecting to my wifi.  Back to the Linux machine to check things in the serial interface.

**Comment by StephenLKearney** [comment]
Okay, I set everything in the serial interface: AP, TXFREQ, RXFREQ, MYCALL, IGATE-HOST, IGATE-PORT, IGATE-USER, IGATE-PASS.  I also did RADIO ON, IGATE ON, DIGI OFF.  For the iGate values, I used:
IGATE-HOST: _noam.aprs2.net_ (see http://www.aprs-is.net/aprsservers.aspx)
IGATE-PORT: _14580_
IGATE-USER: _[same as MYCALL]_
IGATE-PASS: _[my APRS passcode]_

The web interface loads in a browser, but it shows no saved settings.

On the OLED, it shows a GPS location and the Reports Stored value is incrementing.  However, Reports Stored doesn't increase when my HT makes a position report or any other APRS message and nothing shows up on the aprs.fi website.

**Comment by ohanssen** [comment]
When it comes to the web-interface be sure you set the following in the serial interface: 'api-key' - A password or a passphrase. Set the same in the web-interface. 'api-origins' - set it to ".*" (a regex for the hosts allowed to connect). It it still kind of work in progress. I hope to improve it soon. 

To activate the tracker, use the 'tracker on' command in the serial interface.

**Comment by StephenLKearney** [comment]
I have a laptop set up with my SDRplay and Direwolf, and it is able to decode the APRS messages from my BTECH UV-PRO handheld.  I was also able to activate the tracker feature in ArcticTracker on the T-TWR; I can see it transmitting on the SDR display.  However, while Direwolf has no problems with the messages from the handheld, it can't decode the ArcticTracker messages.  

I also couldn't get the ArcticTracker IGATE feature to work reliably, perhaps because of the same factors that prevent the tracker messages from being decoded.

**Comment by ohanssen** [comment]
Transmitting works fine for me. Reception of messages is more problematic and I am working with some improvements. I am working with using the continous mode of the ADC and it is promising. But I also have some issues with the squelch of the SA868.
